import './globals.css'
import { Inter } from 'next/font/google'
import AppContext from '@/context/AppContext'
import Layout from '@/components/Layout'
import { API_KEY } from '../../config'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payment Spliting',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body>
        <Layout>
       <AppContext API_KEY={API_KEY}>
       {children}
       </AppContext>
       </Layout>
        </body>
    </html>
  )
}
