import './globals.css'
import { Inter } from 'next/font/google'
import AppContext from '@/context/AppContext'
import Layout from '@/components/Layout'
import { API_KEY } from '../../config'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payment Spliting',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.png',
  },
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32"  href="./favicon.ico"/>
    <!-- Hotjar Tracking Code for Site 3914480 (name missing) -->
<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:3914480,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>
      </head>
      <body>
        <Layout>
          <AppContext API_KEY={API_KEY}>
            {children}
          </AppContext>
        </Layout>
      </body>
    </html>
  )
}
