import './globals.css'
import { Inter } from 'next/font/google'
import AppContext from '@/context/AppContext'
import Layout from '@/components/Layout'
import { API_KEY } from '../../config'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Payment Spliting',
  description: 'Generated by create next app',
  icons: {
    icon: './favicon.png',
  },
};


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" sizes="32x32"  href="./favicon.ico"/>
    <script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "ljv694sx4n");
</script>
      </head>
      <body>
        <Layout>
          <AppContext API_KEY={API_KEY}>
            {children}
          </AppContext>
        </Layout>
      </body>
    </html>
  )
}
